set nocompatible
set background=dark
syntax on
set fileformats=unix,mac,dos
set history=700
set wildmenu
set incsearch
set hlsearch
set cmdheight=2
set laststatus=2
set list
set listchars=tab:>-,trail:-
set nostartofline
set shell=/bin/bash
set encoding=utf8
set nobackup
set nowb
set noswapfile
set numberwidth=5
set report=0
set ruler
set showcmd
set showmatch
set expandtab
set shiftround
set shiftwidth=4
set softtabstop=4
set tabstop=4
set statusline=%F[%{strlen(&fenc)?&fenc:'none'},%{&ff}]%h%m%r%y%=%c,%l/%L\ %P

